In [9]:
import pandas as pd

portions = 'Portions.csv'
portion_data = 'Portion_data.csv'
nutrients = 'Nutrients.csv'

portions_df = pd.read_csv(portions)
portion_data_df = pd.read_csv(portion_data)
nutrients_df = pd.read_csv(nutrients)

In [10]:
portions_df.head()
nutrients_df.count()

Action                            0
Food_Item_ID                   6454
foodcode                       6454
modcode                        6454
foodname                       6454
                               ...
Calc_Omega3_EPA                6701
Calc_V_TOTAL                   6701
Calc_Protein_Foods             6701
Calc_Protein_Nuts_Seeds_Soy    6701
Calc_Added_Sugars_Grams        6701
Length: 98, dtype: int64

In [ ]:
cleaned_nutrients = nutrients_df.loc[:,]

In [11]:
portions_merge_df = pd.merge(portion_data_df, portions_df, on = 'portion_code', how = 'left')
portions_merge_df.head(100)

,Action_x,Food_Item_ID,foodcode,modcode,foodname,portioncode,portioncode addendum,portion_code,portionwgt,Portion_Factor,portiondesc_x,increment,default portion,Use as default,Active_x,Action_y,portiondesc_y,Active_y
0,NaN,1,11111000,0,"Milk, whole",10205,0,1020500,244.00,2.4,cup,0.25,1,1,1,NaN,cup,1
1,NaN,1,11111000,0,"Milk, whole",10205,3,1020503,244.00,2.4,cup (school carton),0.25,1,0,1,NaN,cup (school carton),1
2,NaN,1,11111000,0,"Milk, whole",21000,0,2100000,15.00,0.2,tablespoon,0.50,1,0,1,NaN,tablespoon,1
3,NaN,1,11111000,0,"Milk, whole",30000,0,3000000,30.50,0.3,fluid ounce(s),1.00,1,0,1,NaN,fluid ounce(s),1
4,NaN,1,11111000,0,"Milk, whole",61795,1,6179501,976.00,9.8,quart (4 cups),0.50,1,0,1,NaN,quart (4 cups),1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,NaN,33,11321100,0,Light chocolate soymilk,30000,0,3000000,30.39,0.3,fluid ounce(s),1.00,1,0,1,NaN,fluid ounce(s),1
96,NaN,33,11321100,0,Light chocolate soymilk,61795,1,6179501,972.00,9.7,quart (4 cups),0.50,1,0,1,NaN,quart (4 cups),1
97,NaN,34,11321200,0,"Milk, soy (soy beverage), fat free (nonfat), c...",10205,0,1020500,243.00,2.4,cup,0.25,1,1,1,NaN,cup,1
98,NaN,34,11321200,0,"Milk, soy (soy beverage), fat free (nonfat), c...",21000,0,2100000,15.18,0.2,tablespoon,0.50,1,0,1,NaN,tablespoon,1
99,NaN,34,11321200,0,"Milk, soy (soy beverage), fat free (nonfat), c...",30000,0,3000000,30.39,0.3,fluid ounce(s),1.00,1,0,1,NaN,fluid ounce(s),1

In [13]:
portions_select_df = portions_merge_df[(portions_merge_df['Use as default'] == 1)]

nutrients_merge_df = pd.merge(nutrients_df, portions_select_df, on = 'foodcode', how = 'left')
nutrients_merge_df.head()

,Action,Food_Item_ID_x,foodcode,modcode_x,foodname_x,_203 Protein (g),_204 Total Fat (g),_205 Carbohydrate (g),_208 Energy (kcal),_221 Alcohol (g),...,portionwgt,Portion_Factor,portiondesc_x,increment,default portion,Use as default,Active_x,Action_y,portiondesc_y,Active_y
0,NaN,1.0,11111000.0,0.0,"Milk, whole",3.1499,3.2500,4.7999,61.0,0.0,...,244.0,2.4,cup,0.25,1.0,1.0,1.0,NaN,cup,1.0
1,NaN,2.0,11111100.0,0.0,"Milk, whole, low-sodium",3.1000,3.4599,4.4599,61.0,0.0,...,244.0,2.4,cup,0.25,1.0,1.0,1.0,NaN,cup,1.0
2,NaN,3.0,11111150.0,0.0,"Milk, whole, calcium fortified",3.1499,3.2500,4.7999,61.0,0.0,...,247.0,2.5,cup,0.25,1.0,1.0,1.0,NaN,cup,1.0
3,NaN,4.0,11111160.0,0.0,"1% milk, calcium fortified",3.3700,0.9700,4.9900,42.0,0.0,...,247.0,2.5,cup,0.25,1.0,1.0,1.0,NaN,cup,1.0
4,NaN,5.0,11111170.0,0.0,"Fat free milk, calcium fortified",3.3999,0.1800,4.8498,35.0,0.0,...,247.0,2.5,cup,0.25,1.0,1.0,1.0,NaN,cup,1.0

In [ ]:
cleaned_nutrients = nutrients_merge_df.loc[:,]

In [ ]:
def FatCals(x):

In [ ]:
def ProteinCals(y):

In [ ]:
def CarbCals(z):

In [ ]:
select_fat = random_fats[(random_fats['Category']=='Fats')