In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import scipy.stats as st
import numpy as np

In [2]:
bodyfat = pd.read_csv("Bodyfat.csv")
bodyfat

,Density,bodyfat,Age,Weight,Height,Neck,Chest,Abdomen,Hip,Thigh,Knee,Ankle,Biceps,Forearm,Wrist
0,1.0708,12.3,23,154.25,67.75,36.2,93.1,85.2,94.5,59.0,37.3,21.9,32.0,27.4,17.1
1,1.0853,6.1,22,173.25,72.25,38.5,93.6,83.0,98.7,58.7,37.3,23.4,30.5,28.9,18.2
2,1.0414,25.3,22,154.00,66.25,34.0,95.8,87.9,99.2,59.6,38.9,24.0,28.8,25.2,16.6
3,1.0751,10.4,26,184.75,72.25,37.4,101.8,86.4,101.2,60.1,37.3,22.8,32.4,29.4,18.2
4,1.0340,28.7,24,184.25,71.25,34.4,97.3,100.0,101.9,63.2,42.2,24.0,32.2,27.7,17.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
247,1.0736,11.0,70,134.25,67.00,34.9,89.2,83.6,88.8,49.6,34.8,21.5,25.6,25.7,18.5
248,1.0236,33.6,72,201.00,69.75,40.9,108.5,105.0,104.5,59.6,40.8,23.2,35.2,28.6,20.1
249,1.0328,29.3,72,186.75,66.00,38.9,111.1,111.5,101.7,60.3,37.3,21.5,31.3,27.2,18.0
250,1.0399,26.0,72,190.75,70.50,38.9,108.3,101.3,97.8,56.0,41.6,22.7,30.5,29.4,19.8
251,1.0271,31.9,74,207.50,70.00,40.8,112.4,108.5,107.1,59.3,42.2,24.6,33.7,30.0,20.9

In [3]:
#import bodyweight for rest burn for males 


standaterdmaledayburn = pd.read_csv("weightlossmen.csv")
standaterdmaledayburn

,Weight(pounds),Calories burned after 8 hours of sitting,Calories burned after 4 hours of sitting and 4 hours of standing,Difference in calories burned over 8 hours,Difference in calories burned per hour
0,100,500,762,262,32.750
1,120,543,828,285,35.625
2,140,587,895,308,38.500
3,160,631,961,330,41.250
4,180,674,1027,353,44.125
5,200,718,1094,376,47.000
6,220,761,1160,399,49.875
7,240,805,1227,422,52.750
8,260,849,1293,444,55.500
9,280,892,1360,468,58.500
10,300,936,1426,490,61.250

In [4]:
#import bodyweight for rest burn for females 

femaledayburn= pd.read_csv("weightlosswomen.csv")
femaledayburn

,Weight(pounds),Calories burned after 8 hours of sitting,Calories burned after 4 hours of sitting and 4 hours of standing,Difference in calories burned over 8 hours,Difference in calories burned per hour
0,100,453,691,238,29.750
1,120,484,737,253,31.625
2,140,514,784,270,33.750
3,160,545,830,285,35.625
4,180,575,877,302,37.750
5,200,606,923,317,39.625
6,220,636,969,333,41.625
7,240,667,1016,349,43.625
8,260,697,1062,365,45.625
9,280,727,1109,382,47.750
10,300,758,1155,397,49.625

In [5]:
#weight input

wwi=input('what is your weight in pounds')

what is your weight in pounds130

In [6]:
#age input
agei= input("whats your age you")

whats your age you25

In [7]:
#workoput time input fake

workouttime=input("how long did you work out dont lie to me ")

how long did you work out dont lie to me 1

In [8]:
#workoput time input real
workouttime2=input("Really tell me how long in to the nearest hour you actuly worked out for " )

Really tell me how long in to the nearest hour you actuly worked out for 1

In [11]:
#fitbit input for heart rate during the workout 
hri=input("what was your avarage heart rate during your workout")

what was your avarage heart rate during your workout160

In [12]:
#gender input 

sex=input("whats your gender m/f")

whats your gender m/fm

In [14]:
#weight rounded to the nearest 20 pounds to match the csv

winpounds= int(20*round(float(wwi)/20.))

#Heart rate veriable
HR = float(hri)
#weight veriable 
W = winpounds/2.2046
#age veriable
A = float(agei)
#time veriable 
T = float(workouttime2)
#create a fork too use the chart 


if sex == "m":
#male    
    caloricburn = ((-55.0969 + (0.6309 * HR) + (0.1988 * W) + (0.2017 * A))/4.184) * 60 * T
else:
#female    
    caloricburn = ((-20.4022 + (0.4472 * HR) - (0.1263 * W) + (0.074 * A))/4.184) * 60 * T

caloricburn

884.9513950406841

In [15]:
#sleep input

sleep=input("how many hours do you sleep a night")

how many hours do you sleep a night12

In [16]:
#standing input
stand=input("how many hours do you stand rounded to the neriest hour")

how many hours do you stand rounded to the neriest hour8

In [17]:
#sitting input 
sit=input("how many hours do you sit in a day to the neriest hour")

how many hours do you sit in a day to the neriest hour3

In [19]:
#resting veriables  


hoursslept= float(sleep)

hoursstanding= float(stand)

hoursworkingout= T

Hourssitting = float(sit)
#diffrentiate the male v female sitting burn

if sex == "m":
    for i, row in standaterdmaledayburn.iterrows():
        if row[0]== winpounds:
                a=row["Calories burned after 8 hours of sitting"]
                b=row['Difference in calories burned per hour']
else:  
    for i, row in femaledayburn.iterrows():
        if row[0]== winpounds:
                a=row["Calories burned after 8 hours of sitting"]
                b=row['Difference in calories burned per hour']
    
        
st=hoursstanding/8
s=Hourssitting/8
z=hoursslept/8  
st1=(a*st)+((b*hoursstanding))

y= (a*z)+(a*s) + caloricburn +st1




        
print(y)

2731.076395040684